// this file was automatically generated by tmx2c. 
#ifndef FIELD_BACKGROUND_MAP_INCLUDE_H
#define FIELD_BACKGROUND_MAP_INCLUDE_H

#include "engine\map_types.h"

RESOURCE() extern const Ruby_StripMap const field_background_map;

#endif
