// File generated by gg2c.
#ifndef BULLET_ANIMATION_INCLUDE_H
#define BULLET_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const Ruby_Animation bullet;

#define BULLET_NUMFRAMES 1

#endif

