// File generated by gg2c.
#ifndef DELIVERYROBOT_ANIMATION_INCLUDE_H
#define DELIVERYROBOT_ANIMATION_INCLUDE_H

#include "engine\AnimationTypes.h"

RESOURCE() extern const GGAnimation deliveryrobot;

#endif

