// File generated by gg2c.
#ifndef ENEMY_BULLET_ANIMATION_INCLUDE_H
#define ENEMY_BULLET_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const Ruby_Animation enemy_bullet;

#define ENEMY_BULLET_NUMFRAMES 2

#endif

