// File generated by gg2c.
#ifndef ENEMY_BULLET_ANIMATION_INCLUDE_H
#define ENEMY_BULLET_ANIMATION_INCLUDE_H

#include "engine\AnimationTypes.h"

RESOURCE() extern const GGAnimation enemy_bullet;

#endif

