// File generated by gg2c.
#ifndef EXPLOSION_ANIMATION_INCLUDE_H
#define EXPLOSION_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const Ruby_Animation explosion;

#define EXPLOSION_NUMFRAMES 9

#endif

