// File generated by gg2c.
#ifndef IMPACT_ANIMATION_INCLUDE_H
#define IMPACT_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const GGAnimation impact;

#define IMPACT_NUMFRAMES 3

// frame numbers for specific animations.
#define IMPACT_8_FRAME_INDEX 0
#define IMPACT_8_FRAME_INDEX 0

#endif

