// File generated by gg2c.
#ifndef ROBOTRUNNER_ANIMATION_INCLUDE_H
#define ROBOTRUNNER_ANIMATION_INCLUDE_H

#include "engine\AnimationTypes.h"

RESOURCE() extern const GGAnimation robotrunner;

#endif

