// File generated by gg2c.
#ifndef ROBOTSPRING_ANIMATION_INCLUDE_H
#define ROBOTSPRING_ANIMATION_INCLUDE_H

#include "engine\AnimationTypes.h"

RESOURCE() extern const GGAnimation robotspring;

#endif

