// File generated by gg2c.
#ifndef ROBOTRUNNER_ANIMATION_INCLUDE_H
#define ROBOTRUNNER_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const GGAnimation robotrunner;

#define ROBOTRUNNER_NUMFRAMES 4

// frame numbers for specific animations.
#define ROBOTRUNNER_RUN_RIGHT_FRAME_INDEX 0
#define ROBOTRUNNER_RUN_LEFT_FRAME_INDEX 2

#endif

