// File generated by gg2c.
#ifndef ROBOTSPRING_ANIMATION_INCLUDE_H
#define ROBOTSPRING_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const Ruby_Animation robotspring;

#define ROBOTSPRING_NUMFRAMES 3

#endif

