// File generated by gg2c.
#ifndef RUBY_ANIMATION_INCLUDE_H
#define RUBY_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const GGAnimation ruby;

#define RUBY_NUMFRAMES 6

// frame numbers for specific animations.
#define RUBY_RUN_RIGHT_FRAME_INDEX 0

#endif

