// File generated by gg2c.
#ifndef SHOTGUN_ITEM_ANIMATION_INCLUDE_H
#define SHOTGUN_ITEM_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const Ruby_Animation shotgun_item;

#define SHOTGUN_ITEM_NUMFRAMES 1

#endif

