// File generated by gg2c.
#ifndef SHOTGUN_ITEM_ANIMATION_INCLUDE_H
#define SHOTGUN_ITEM_ANIMATION_INCLUDE_H

#include "engine\AnimationTypes.h"

RESOURCE() extern const GGAnimation shotgun_item;

#endif

