// File generated by gg2c.
#ifndef SHOTGUN_ANIMATION_INCLUDE_H
#define SHOTGUN_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const Ruby_Animation shotgun;

#define SHOTGUN_NUMFRAMES 3

// frame numbers for specific animations.
#define SHOTGUN_RUN_RIGHT_FRAME_INDEX 0

#endif

