// File generated by gg2c.
#ifndef THREESHOTFLYER_ANIMATION_INCLUDE_H
#define THREESHOTFLYER_ANIMATION_INCLUDE_H

#include "engine\AnimationTypes.h"

RESOURCE() extern const GGAnimation threeshotflyer;

#endif

