// File generated by gg2c.
#ifndef THREESHOTFLYER_ANIMATION_INCLUDE_H
#define THREESHOTFLYER_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const GGAnimation threeshotflyer;

#define THREESHOTFLYER_NUMFRAMES 2

#endif

