// File generated by gg2c.
#ifndef WALKER_ANIMATION_INCLUDE_H
#define WALKER_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const Ruby_Animation walker;

#define WALKER_NUMFRAMES 2

#endif

