// File generated by gg2c.
#ifndef WALKER_SMALL_ANIMATION_INCLUDE_H
#define WALKER_SMALL_ANIMATION_INCLUDE_H

#include "engine\AnimationTypes.h"

RESOURCE() extern const GGAnimation walker_small;

#endif

