// File generated by gg2c.
#ifndef WHEELER_ANIMATION_INCLUDE_H
#define WHEELER_ANIMATION_INCLUDE_H

#include "engine\animation_types.h"

RESOURCE() extern const GGAnimation wheeler;

#define WHEELER_NUMFRAMES 11

// frame numbers for specific animations.
#define WHEELER_RUN_RIGHT_FRAME_INDEX 0
#define WHEELER_RUN_LEFT_FRAME_INDEX 2
#define WHEELER_SHOCK_FRAME_INDEX 4
#define WHEELER_SENTRY_FRAME_INDEX 5
#define WHEELER_PARTS_HEAD_FRAME_INDEX 7
#define WHEELER_PARTS_ARM1_FRAME_INDEX 8
#define WHEELER_PARTS_ARM2_FRAME_INDEX 9
#define WHEELER_PARTS_WHEEL_FRAME_INDEX 10

#endif

