// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef GLOBAL_PALETTE_PALETTE_INCLUDE_H
#define GLOBAL_PALETTE_PALETTE_INCLUDE_H

#include "palette_types.h"
#include "resource_types.h"

RESOURCE() extern const PaletteResource global_palette;

#endif

